### ISSUE TITLE
Missing unit VSoftVirtualListView for DPM.IDE.dll

### ISSUE THREAD

**Issue by pipcom** [DelphiPackageManager/DPM#10]
I am not able to compile DPM.IDE.dll project because of missing VSoftVirtualListView unit in DPM.IDE.EditorViewFrame.
I searched a while but i did not find it. In which project can i find it ?

**Comment by vincentparrett** [comment]
That is here : https://github.com/VSoftTechnologies/VSoft.VirtualListView

Probably worth adding to your batch file!

Note that DPM is very much a work in progress, especially the IDE integration. Debugging IDE plugins is death with a thousand cuts, slow and painful. I'm currently working on adding the packages to the project tree, but there is no published api for that so I'm hacking away at the IDE using RTTI and some guesswork. I have that working, but not reliably (timing issues).
