### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by limelect** [DelphiPackageManager/DPM#15]
D10.2.3
in unit DPM.Core.Package.Installer;
line 535-554
 projectReferences.AddRange(TEnumerable.Select<IPackageInfo, TProjectReference>(projectPackageInfos,
    function(const info : IPackageInfo) : TProjectReference

DPM.Core.Package.Interfaces.IPackageInfo,DPM.Core.Dependency.Interfaces.TProjectReference>' that can be called with these arguments

**Comment by vincentparrett** [comment]
What version of Spring4D are you using? You need to use the develop branch

https://bitbucket.org/sglienke/spring4d/branch/develop

**Comment by limelect** [comment]
Same problem
And further more read-only
DPM.IDE.EditorViewFrame;
631  FScrollList.CurrentRow := -1;
638  FScrollList.CurrentRow := 0;
779  FScrollList.CurrentRow := -1;

**Comment by vincentparrett** [comment]
What version of delphi?

**Comment by vincentparrett** [comment]
To me those errors indicate you are not using the latest versions of the virtual list view package and the spring4d. 

Try cleaning out your package cache folder C:\Users\[Username]\AppData\Roaming\.dpm\packages

I have updated the [Getting Started page](https://github.com/DelphiPackageManager/DPM/blob/master/GettingStarted.md) - in particular the build section about creating the missing packages.

**Comment by vincentparrett** [comment]
I just added a fresh virtuallistview release and updated the projects to use it - it built fine on my machine and the CI server.

**Comment by limelect** [comment]
D10.2.3 new download
If i compile dpm.dpr i have more problems
DPM.IDE.D102.dpr same problems
Give up good luck

**Comment by vincentparrett** [comment]
I'd like to help you but you haven't actually told me what steps you followed. This is harder than the average project as it's bootstrapping itself.

**Comment by limelect** [comment]
Very simple could not compile on D10.2.3

This is what i got as you can see

in unit DPM.Core.Package.Installer;
line 535-554
projectReferences.AddRange(TEnumerable.Select<IPackageInfo, TProjectReference>(projectPackageInfos,
function(const info : IPackageInfo) : TProjectReference

DPM.Core.Package.Interfaces.IPackageInfo,DPM.Core.Dependency.Interfaces.TProjectReference>' that can be called with these arguments

In order to help you will let you connect with TEAM VIEWER to my d10.2.3
