### ISSUE TITLE
Installing in Rad Studio 10.4 results in unrecoverable error when loading IDE

### ISSUE THREAD

**Issue by rmcginty** [DelphiPackageManager/DPM#22]
After installing the latest release (0.1.75) into 10.4, I received a message box saying:

Failed to load wizard splash image

Hitting Ok results in being spammed with access violations in RTL270.BPL and I have to terminate BDS.exe manually.  Uninstalling the package fixes the issue.

My exact version of 10.4, according to the about screen, is 10.4 Version 27.0.37889.9797.  This is basically vanilla 10.4 with patches 1 - 3 applied.

**Comment by vincentparrett** [comment]
I am building with the latest update releases - since it's not possible to install 10.4 10.4.1 10.4.2 on the same machine there is not much I can do about that. Normally there would be binary compatibility between those releases, but I believe the 10.4 releases all had compatibility issues.

**Comment by rmcginty** [comment]
I had a feeling that was the case.  I've been unable to get 10.4.2 installed properly, so I'm still stuck on a patched version of 10.4 for right now.  I may play with the source in the meantime.  Thanks!
