### ISSUE TITLE
Is it really necessary to have another dependency manager since there are 3 or more opensource?

### ISSUE THREAD

**Issue by EdZava** [DelphiPackageManager/DPM#27]
Some project examples I know:

- https://github.com/jcangas/DelphiVM
- https://github.com/HashLoad/boss
- https://github.com/Memnarch/Delphinus
- https://github.com/corneliusdavid/AutoGetIt

It would be interesting to at least use them as a base, so as not to reinvent the zero wheel.

But looking at the documentation of your project it looks quite interesting. Better than the other projects cited above that don't have documentation.

What I did not find in the documentation, is how will the installation of components be, will it be by project? how can you support third party packages, like TMS, DevExpress?

I am currently using "DelphiVM" and we do almost everything by hand too.

**Comment by vincentparrett** [comment]
DelphiVM - abandoned - written in ruby?
Hashload - written in Go
Delphinus - doesn' work in the same way
AutoGetit - a hack to improve Getit (which is a toy). 

This PM is written entirely in Delphi, does per project package versioning, full dependency resolution. It's not yet complete, and the doco is out of date. I will update the doco when the PM is more completey. 

As for third parties, they will need to create packages - it's a bit early yet as we are not at the stage where it's usable for eveyone (still working on design time component loading). I have had discussions with TMS and others.

**Comment by EdZava** [comment]
The truth is that many have already tried it in different languages, but each one focused on solving their own problem and then released the project as OpenSource, leaving it there dead without maintenance or hope for improvements.

I hope this project will be better than the others and that we can finally have a decent dependency manager for Delphi. Embarcadero doesn't seem to care about its customers and doesn't make significant improvements; they appear more focused on selling and claiming that they are doing something. We haven't had significant advancements in either the language or the IDE for years.

I hope I can help, whether with ideas, proposals, or even programming if I can assist with the project in any way. It's my hope that this moves forward and becomes a reality.

Lo siento por mi pesimo ingles. By Google translate 😉

**Comment by EdZava** [comment]
I'm sorry I didn't see that there was a project for RFCs and then I moved the question there too. But I'm going to close it.
