### ISSUE TITLE
missing creating-packages doc file

### ISSUE THREAD

**Issue by birbilis** [DelphiPackageManager/DPM#35]
at
https://github.com/DelphiPackageManager/DPM/blame/master/docs/concepts/how-it-works.md
there is a broken link to creating-packages.md (it is missing)

but I wonder if the docs folder there is up to date, since there's a doc repository that is separate (https://github.com/DelphiPackageManager/docs) and which must contain creating-packages since it generates
https://docs.delphi.dev/getting-started/creating-packages.html
fine

**Comment by vincentparrett** [comment]
The correct docs are in the separate repo. I just hadn't gotten around to removing them from the main repo.
