### ISSUE TITLE
v0.2.84-alpha Installer doesn't create the packages folder 

### ISSUE THREAD

**Issue by malcolmgroves** [DelphiPackageManager/DPM#36]
Installed using v0.2.84-alpha, "me only". Delphi 12.1.

Installer created the .dpm folder, but not the packages folder under it. When trying to install a package using the IDE integration, exception thrown due to unknown folder.

Creating the packages folder manually fixed it, no issues.

**Comment by vincentparrett** [comment]
thanks, will fix.

**Comment by vincentparrett** [comment]
Fixed.
